name: First-GitHub-Workflow	

on: 
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout the source
        uses: actions/checkout@v3
        
      - name: Run a basic command
        run: echo Hello from GitHub Actions!
      
      - name: Run a multi-line script
        run: |
          echo Running multi-line action
          echo CI-CD platform.

